name:                lc
version:             0.1.0.0
github:              "lbuchli/lc"
license:             BSD3
author:              "Lukas Buchli"
maintainer:          "lukas@buchli-bigger.ch"
copyright:           "2020 Lukas Buchli"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lbuchli/lc#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- random
- tasty
- smallcheck
- tasty-smallcheck
- tasty-hunit
- tasty-discover

library:
  source-dirs: src

executables:
  lc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lc

tests:
  lc-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lc
